### ISSUE TITLE
Revisi frontend table

### ISSUE THREAD

**Issue by syauqiahmd** [syauqiahmd/e-Commerce#17]
- [x] ubah style table

- [x] ubah style button di table (using sm)

- [x] perbaikan colom search

**Comment by FaruqRahmadani** [comment]
lwn anu qi, double initial, tp ada sudah ku baiki di #15, tgg di merge dari sana aja kah?

**Comment by syauqiahmd** [comment]
wokeh dimerge dari branch #15 aja.... udah ku merge ke #11
